name: Terraform GKE Cluster

on:
  push:
    branches:
      - main

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        service_account_key: ${{ env.GOOGLE_CREDENTIALS }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        version: 0.14.0

    - name: Apply Terraform
      run: |
        terraform init
        terraform apply -auto-approve
